site_name: Telekinesis URDFs Documentation
theme: readthedocs

nav:
  - Loader: loader.md
  - Utils: utils.md
  - Registry: registry.md

not_in_nav: |
  index.md

extra_css:
  - styles/mkdocstrings-spacing.css

hooks:
  - docs/hooks/generate_registry.py

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
